[workspace]
members = ["devkit-rl"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
