[package]
name = "devkit-rl"
version = "0.1.0"
edition = "2021"
authors = ["hedonwang"]

[[bench]]
name = "token_bucket_bench"
harness = false

[[bench]]
name = "leaky_bucket_bench"
harness = false

[dependencies]
chrono = "0.4.38"
criterion = { workspace = true }
oneshot = "0.1.8"
